Fixed internal protection level of asyncMap
shareup/async-extensions pull request #6
Opened 2022-10-04 12:40 UTC by sashkopotapov

2022-10-04 13:05 UTC, atdrendel requested changes
Let's write a test for this. That would have caught this problem.

2022-10-04 17:39 UTC, sashkopotapov commented on Tests/AsyncExtensionsTests/SequenceExtensionsTests.swift
> +    }
@atdrendel  you were super right about the tests, because I needed `concurrentMap`, not `asyncMap`

2022-10-04 20:16 UTC, atdrendel commented on Sources/AsyncExtensions/SequenceExtensions.swift
> +///
```suggestion
```

2022-10-04 20:50 UTC, atdrendel commented
@sashkopotapov As a rule, we shouldn't ever try to test how long something takes. First, it doesn't actually tell us if the code works properly. Second, it's really unreliable. Third, it makes the tests take way too long.

So, I modified the tests to make sure `asyncMap()` processes tasks serially and `concurrentMap()` tries to process them in parallel. Also, I added simple tests to make sure the two functions actually give us the right answers. You can see the improvement in test run times below:

Before: 
<img width="633" alt="CleanShot 2022-10-04 at 22 41 11@2x" src="https://user-images.githubusercontent.com/202402/193925137-b9334e13-6b9d-407f-92cb-941babc5504d.png">

After:
<img width="633" alt="CleanShot 2022-10-04 at 22 45 56@2x" src="https://user-images.githubusercontent.com/202402/193925169-e556489c-c28c-42c9-8a82-b4ff26bb6015.png">

2022-10-04 20:50 UTC, atdrendel approved these changes

2022-10-05 08:11 UTC, atdrendel commented on Tests/AsyncExtensionsTests/SequenceExtensionsTests.swift
> +
```suggestion
```

2022-10-05 08:59 UTC, merged